import 'package:dalalat_quran_light/controllers/add_reserch_controller.dart';
import 'package:dalalat_quran_light/controllers/article_series_controller.dart';
import 'package:dalalat_quran_light/controllers/articles_controller.dart';
import 'package:dalalat_quran_light/controllers/comment_controller.dart';
import 'package:dalalat_quran_light/controllers/correct_word_controller.dart';
import 'package:dalalat_quran_light/controllers/download_link_controller.dart';
import 'package:dalalat_quran_light/controllers/explanation_controller.dart';
import 'package:dalalat_quran_light/controllers/get_article_controller.dart';
import 'package:dalalat_quran_light/controllers/get_study_controller.dart';
import 'package:dalalat_quran_light/controllers/get_tag_controller.dart';
import 'package:dalalat_quran_light/controllers/read_aya_controller.dart';
import 'package:dalalat_quran_light/controllers/settings_controller.dart';
import 'package:dalalat_quran_light/controllers/similar_word_controller.dart';
import 'package:dalalat_quran_light/controllers/studies_controller.dart';
import 'package:dalalat_quran_light/controllers/tags_screen_controller.dart';
import 'package:dalalat_quran_light/controllers/video_controller.dart';
import 'package:dalalat_quran_light/controllers/video_series_controller.dart';
import 'package:dalalat_quran_light/controllers/word_tag_controller.dart';
import 'package:dalalat_quran_light/features/chat/controller/chat_controller.dart';
import 'package:dalalat_quran_light/features/discussions/controllers/discussion_controller.dart';
import 'package:dalalat_quran_light/features/grammer_rules/controllers/grammer_ayahs_controller.dart';
import 'package:dalalat_quran_light/features/grammer_rules/controllers/grammer_controller.dart';
import 'package:dalalat_quran_light/features/grammer_rules/controllers/grammer_surahs_controller.dart';
import 'package:dalalat_quran_light/features/notifications/controllers/notifications_controller.dart';
import 'package:dalalat_quran_light/features/quran/controllers/quran_reader_controller.dart';
import 'package:dalalat_quran_light/features/quran/controllers/surah_list_controller.dart';
import 'package:dalalat_quran_light/features/words/controllers/quran_roots_search_controller.dart';
import 'package:dalalat_quran_light/features/words/controllers/roots_controller.dart';
import 'package:dalalat_quran_light/features/words/controllers/verses_controller.dart';
import 'package:dalalat_quran_light/network/sync_manager.dart';
import 'package:dalalat_quran_light/utils/servicle_locator.dart';
import 'package:get/get.dart';

void initializeGetController() {
  Get.put(SyncManager()..syncData(), permanent: true);
  Get.put(CommentController(dioConsumer: serviceLocator()), permanent: true);
  Get.put(ExplanationController(dioConsumer: serviceLocator()), permanent: true);
  Get.put(AddResearchController(dioConsumer: serviceLocator()), permanent: true);
  Get.put(GetDownloadLinkController(dioConsumer: serviceLocator()), permanent: true);
  Get.put(VideoController(), permanent: true);
  Get.put(WordTagController(), permanent: true);
  Get.put(SettingsController(), permanent: true);
  Get.put(ArticlesController(), permanent: true);
  Get.put(TagsScreenController(), permanent: true);
  Get.put(ArticlesSeriesController(), permanent: true);
  Get.put(GetArticleController(), permanent: true);
  Get.put(GetTagController(), permanent: true);
  Get.put(VideosSeriesController(), permanent: true);
  Get.put(ReadAyaController(), permanent: true);
  Get.put(SimilarWordController(), permanent: true);
  Get.put(CorrectWordController(), permanent: true);
  Get.put(ChatController()..init(), permanent: true);
  Get.put(GrammerRulesController(), permanent: true);
  Get.put(GrammerSurahsController(), permanent: true);
  Get.put(GrammerAyahsController(), permanent: true);
  Get.put(DiscussionController(), permanent: true);
  Get.put(StudiesController(), permanent: true);
  Get.put(GetStudyController(), permanent: true);
  Get.put(RootsController(), permanent: true);
  Get.put(VersesController(), permanent: true);
  Get.put(QuranRootsSearchController(), permanent: true);
  Get.put(NotificationsController(), permanent: true);
  Get.put(SurahListController(), permanent: true);
  Get.put(QuranReaderController(), permanent: true);
}
